### ISSUE TITLE
Displaying random characters

### ISSUE THREAD

**Issue by MaxTretikov** [shufflebits/GU140X32F-7703A_Adafruit_GFX#2]
My display is definitely a GU140x32F-7703A, but none of the examples are working. Instead, it outputs random characters from the internal font set repeatedly. Each pin should be plugged in correctly. On an elegoo uno r3 if that makes a difference.

**Comment by MaxTretikov** [comment]
Doing some byte-level testing:
```cpp
    // vfd.vfdWrite8('J'); // 0x4A (01001010)
    // printing 'F' 0x50 (01010000)

    // vfd.vfdWrite8('n'); // 0x6E (01101110)
    // printing '≡' 0xF0 (11110000)
```
My first instinct on seeing the first example was that it looked like it was bit-shifted left 3 places, so maybe we were missing a clock cycle or something. But the second example is even stranger, since there's 4 bits that don't exist at all in the original byte

**Comment by MaxTretikov** [comment]
I also found [this forum thread](https://forum.arduino.cc/t/noritake-itron-gu-7xxx-vfd/193138), the code of which works perfectly well for me. Something is fundamentally wrong with `vfdWrite8` on my side. I'm wondering if I need to close some of the jumpers into synchronous mode (everything is as it was out of the factory), but they don't look closed in the pictures. Closing J2 seems to do a whole lotta nothing.

**Comment by MaxTretikov** [comment]
Given the SoftwareSerial with a baudrate of 38400 looks to be working, I'm almost certainly in asynchronous mode with the default settings, but connecting J2 with a jumper and resetting results in exactly the same problem. I'm at a loss here.

**Comment by MaxTretikov** [comment]
Well, I'm an idiot. Connecting J2 *does* do something when your cable isn't loose and touching the ground. 🤦

Going to solder it together, but it looks like that's all you need to get the sync interface working.

**Comment by shufflebits** [comment]
Glad I could be with you on the journey! :-)
